Time independent skulltulas
OoTRandomizer/OoT-Randomizer pull request #2332
Opened 2024-11-18 03:03 UTC by mracsys

Opening as draft. Feature isn’t fully implemented, only a proof of concept so far.

Two parts to this PR. There is the skulltula time of day feature, and a new framework to enable arbitrary changes to any of the scene or room files parsed to linked python objects. The framework automatically shifts all pointers within the files to handle new file locations and additions/deletions within the file. It will have multiple applications besides the skulltula feature:

* Detailed cutscene parsing instead of writing raw bytes (WIP). Also more easily allows writing completely new cutscenes.
* Adding any actor/object to any room, such as a sign outside Ganon’s castle for the bridge condition or anywhere else a hint might be helpful
* Entrance/exit additions, such as promoting grottos to the same framework as other entrances, or new loading planes for mixed pool door rando
* Space reclamation. Almost a MB is wasted in padding between scene and room files.
* More user friendly interface for MQ patching, and opens the door for other alternate scene options for anyone crazy enough to attempt it.
* Collision changes for problems like #2331 and for my vision of door rando without scene reloads between doors.

Todo:

- [ ] Test compressed roms. DMA changes for compressor?
- [ ] Update pointers outside scene files to globals in them, mainly cutscenes.
- [ ] If 2 doesn’t fix problems moving file start addresses, figure that out
- [ ] Integrate framework with rando patching pipeline
- [ ] Move cutscene patches to framework
- [ ] Move MQ patching to framework
- [ ] Move any other scene changes to framework
- [ ] Add setting for skulltulas ignoring time of day. Add actors/objects where needed and patch all actor parameters.

2024-11-18 07:07 UTC, r0bd0g commented
I guess for logic you go around to each skulltula you affected and change at_night to (at_night or [setting]). Something to look out for is the watchtower, which will no longer be climbable in child day without a means of killing the skulltula.

2025-03-11 05:58 UTC, mzxrules commented on ProcessActors.py
> +#rom = Rom("ZOOTDEC.z64")
what's with all the dead code here

2025-03-11 05:58 UTC, mzxrules commented on Scene.py
> +    #check_external_reference_locations(uncompressed_rom)
more dead code

2025-03-11 05:58 UTC, mzxrules commented on Cutscenes.py
> +class CutsceneCommandID(IntEnum):
man, rando sure is a hot mess when it comes to organization. 

I find it kind of odd to just stuff these important type definitions after a bunch of function patching routines split out of patches.py. I think we need to consider moving this type access stuff into a new folder like "z64types" or something

2025-03-12 05:05 UTC, mracsys commented on Cutscenes.py
> +class CutsceneCommandID(IntEnum):
You're right, I should have put more effort into structure. Some of the other utility classes like `Vec3s` and `Vec3i` that didn't fit well got put into Rom.py despite not fitting there either. I can refactor into the same file/folder structure as decomp for structs lifted from there, with a top level folder to keep it neat.

2025-03-12 05:06 UTC, mracsys commented on ProcessActors.py
> +#rom = Rom("ZOOTDEC.z64")
This is a utility script from @rrealmuto used on his branch. Some of this was already in the main repo. I can remove the whole file if needed and its not inconvenient to Rob.

2025-03-12 05:06 UTC, mracsys commented on Scene.py
> +    #check_external_reference_locations(uncompressed_rom)
removed

2025-03-12 23:19 UTC, r0bd0g commented
I warned you about special logic that would be needed for KF GS Know It All House! As you have it currently, in closed forest, if you start at daytime, the skulltula will be there but you won't have logic to collect it before beating forest or finding sun's song. That skull has an extra check on it to make sure you can actually get it since closed forest breaks the assumption that you will always have access to moving time of day from spawn, so you need to add the new setting as an alternative way to have the time of day to access it.

(This isn't really related to your PR, you shouldn't change anything about this, but I wonder if all of those skulltulas that check for ToD in areas where time moves already, should just have the time of day check removed. It was nice to look at before but with the new setting it's become kind of bloated. I made a choice along those lines with Peahats when reviewing enemy shuffle b/c separate night and day logic for them was pretty convoluted for no real benefit.)

I don't know enough about glitched to say whether or not the logic is wrong absolutely for sure or not, but at a glance I don't trust it. For example, man on roof, you check for a weapon to kill the skulltula, but you always are checking it regardless of if the skulltula is potentially there at daytime. You should get a glitched logic expert to review it.

(Unrelated to your PR but I was glancing over the night skulls and noticed some logic for buying the Giant's Knife that is assuming that the Knife isn't shuffled. This shows the dangers of marking new settings as glitched logic compatible without getting a specialist's review!)

2025-03-23 17:25 UTC, fenhl commented
Should this setting be enabled in the Easy Mode preset?

2025-03-23 17:47 UTC, mracsys commented
It would make sense. Would that need to go through some sort of vote or poll?

2025-03-23 17:59 UTC, fenhl commented
Current dev team call is in favor so I'd say you can just add it.

2025-03-24 19:01 UTC, shirosoluna commented
@r0bd0g > 
> I don't know enough about glitched to say whether or not the logic is wrong absolutely for sure or not, but at a glance I don't trust it. For example, man on roof, you check for a weapon to kill the skulltula, but you always are checking it regardless of if the skulltula is potentially there at daytime. You should get a glitched logic expert to review it, or make no glitched logic changes and mark the settings as incompatible.
> 
> (Unrelated to your PR but I was glancing over the night skulls in glitched logic and noticed some logic for buying the Giant's Knife that is assuming that the Knife isn't shuffled. This shows the dangers of marking new settings as glitched logic compatible without getting a specialist's review!)

I wouldnt worry too much about glitched logic right now, because it's being updated entirely to have all settings included. There are way more important stuff that isnt compatible at all currently and in released versions. If this is going to be slated for 9.0 as well then we can make it incorporated. I dont know the timing for this PR. 
Just offering support to not be concerned about glitched logic too too much atm

2025-03-24 19:09 UTC, fenhl commented
There's not really any timing for this PR, it will be merged once it's been code reviewed and sufficiently tested. Since it's a rather large change, that might take a while, but so is glitched logic 3.0, so it's hard to say which is more likely to be merged first. I'd recommend not including the changes for this in glitched logic 3.0 for now or perhaps maintaining them separately.

2025-03-27 21:25 UTC, shirosoluna commented
> There's not really any timing for this PR, it will be merged once it's been code reviewed and sufficiently tested. Since it's a rather large change, that might take a while, but so is glitched logic 3.0, so it's hard to say which is more likely to be merged first. I'd recommend not including the changes for this in glitched logic 3.0 for now or perhaps maintaining them separately.

wasn't meaning that it would wait for it but that I'd incorporate it into logic when the time comes. Even if it's after being pulled. 
They are maintained separately. But if new glitch logic comes later then still dont bother worry about current glitched logic. It's too incompatible with everything currently and one more setting wouldnt make a difference lol.

2025-06-02 23:57 UTC, fenhl requested changes

2025-06-02 23:57 UTC, fenhl commented on ASM/src/hacks.asm
> +;    .byte 0xFF ; Set generic grotto text ID to load from grotto ID
Any reason this is commented out? If it's not necessary anymore, it'd be better to just remove it.

2025-06-02 23:57 UTC, fenhl commented on Patches.py
> +    #         patch_actor_override(location, rom)
This can be removed, it's no longer needed since these were refactored in potsanity 3.0.

2025-06-02 23:57 UTC, fenhl commented on ProcessActors.py
> +#rom = Rom("ZOOTDEC.z64")
Rob says it's fine to remove it.

2025-06-03 00:03 UTC, fenhl commented
I'll see if we can get a web generator for this branch set up to encourage more testing.

2025-06-05 00:57 UTC, mracsys commented on ASM/src/hacks.asm
> +;    .byte 0xFF ; Set generic grotto text ID to load from grotto ID
Nope, missed this when I was cleaning up all the old stuff I kept for reference.

2025-06-05 01:07 UTC, mracsys commented
FYI, I don't have much free time through at least fall, possibly into next year. I'm still around, but changes might be delayed.

2025-06-05 01:24 UTC, fenhl approved these changes

2025-07-20 12:35 UTC, fenhl commented
This PR branch is now available as a web generator at <https://ootrandomizer.com/generatorDev?version=devM_> (ignore the “currently unmaintained” in the title, it is up to date with the PR). Any feedback from people testing it would be appreciated, even if that feedback is “everything worked well”.

2025-08-28 20:41 UTC, mracsys commented
I'm done with changes to this pending additional reviews.

2025-11-12 02:04 UTC, rrealmuto commented on Gui.py
Came here because I wanted to steal your virtual environment code. I think I had mentioned this previously but checking for/creating the venv in Gui.py is not sufficient. Gui.py is not invoked in the release build. Instead electron is started directly using node.

I have a semi-working implementation of creating the venv and updating packages from javascript in #2143 which generally works with the release build. However the lack of solid error handling has been what has stopped me from merging this on my branch already

2026-02-03 07:45 UTC, fenhl commented on Gui.py
Do you think you two could combine your efforts to add something that'll work for both use-cases to this PR?

2026-02-03 07:58 UTC, fenhl requested changes
@rrealmuto's concerns about the venv handling still need to be addressed. Other than that, this looks good to me.

2026-02-08 18:10 UTC, mracsys commented
@rrealmuto Can you point me to where the problem is? I built the installer in a fresh Windows environment and had no problems with the installed release build making it's own venv in its appdata folder. Also tested on Linux. requirements.txt needs to be manually copied into the GUI/python subfolder on build along with all the other files.

The function to create the venv lives in Gui.py, but it's called in OoTRandomizer.py and CI.py as well to handle those use cases.

2026-03-01 02:54 UTC, mracsys commented
Error reporting if pip fails is handled for dev and release. An error is thrown with the pip stderr output from python, which is captured by the GUI when starting the application (independent of launching through `Gui.py`). I tested it by disconnecting from the internet and removing the `.venv` folder and attempting to launch. The GUI has a loading icon preventing interaction on everything except the patch area at the bottom until the venv is either created or fails (with error display). I can't test failures on web, though if I understand the architecture there correctly, the venv is created once on first visit for all users. Any errors there would be quickly apparent on branch update, and presumably would have the immediate attention of the dev pushing the branch.

@rrealmuto does this address your concerns?

I also rebased to 9.x, which includes integrating advanced logic. @shirosoluna would you mind taking a look to make sure I got everything right?

2026-03-04 21:03 UTC, fenhl commented
I pinged @rrealmuto on Discord and this was the reply:

> I read his comment. Still don't think any of the venv code should be done in Gui.py this is literally exactly what trez and DB told me not to do.

> Gui.py doesn't get called by the release build

> I have a (somewhat) robust venv setup that gets handled in the electron code. Displays status during the setup and reports errors on the GUI. 
>
> Both of these solutions run into the issue that you won't have the dependencies if you don't launch the GUI. So they don't work for 1) the web and 2) any CLI users without first having the dependencies installed

Personally I don't think that's a big issue since we can add instructions for CLI users to install the deps, and we're currently discussing how to make things work on the website in a disk-space-efficient manner. (Backwards-incompatible dependency upgrades will likely need to be kept to a minimum so venvs can be reused across randomizer versions.)

2026-03-04 22:36 UTC, mracsys commented
Like I've said a few times, the venv setup is called by the CLI entry scripts (Ootrandomizer.py and CI.py). Gui.py also runs it independent of any of the CLI entries for anyone using the randomizer that way, but it is not the only path for venv creation. I've tested all of this on fresh python installs for CLI, GUI, and release builds. None of it depends solely on the GUI. The function is imported from Gui.py because it has to live somewhere. I can move that to Ootrandomizer.py, Rom.py, Main.py, or wherever is preferred.

I can add a version header to the requirements.txt file in a comment if that makes web deduplication easier.

2026-03-05 01:01 UTC, flagrama commented
I think the most appropriate existing file would be Utils. Otherwise a new file.

I definitely do not expect to find virtual env information in Gui.py or Ootrandomizer.py. Including Main.py just sounds like bad practice (regardless of if we already do it elsewhere, I did not check).

2026-03-05 01:04 UTC, rrealmuto commented
Talked to mracsys and no more concerns on the venv bit

2026-03-05 02:15 UTC, mracsys commented
I need to apologize for getting snippy in my last message. I wasn't understanding what I was failing to communicate, but that's not an excuse. Things resolved quickly on Discord. I expanded more on the venv system in the PR description for posterity. Thanks again Rob!

2026-03-05 03:32 UTC, fenhl approved these changes

2026-03-05 03:39 UTC, fenhl commented
Thank you for sorting this out. I should apologize as well for not realizing what the misunderstanding was, I could have caught that if I'd paid closer attention.

The website is being updated with venv support and I've requested an update for the devM generator so I can call for another round of testing.

2026-03-07 18:42 UTC, shirosoluna commented on data/Glitched World/Overworld.json
> +                or (is_child and ((at_day and not gold_skulls_ignore_daytime) or
I think this was added in error? I think you may have just looked for at_day and added the skull helper. This one can be removed since it is just access to the area not skull related

2026-03-07 18:50 UTC, fenhl commented on data/Glitched World/Overworld.json
> +                or (is_child and ((at_day and not gold_skulls_ignore_daytime) or
This is for getting onto granny's potion shop's roof via the watchtower, so the skull is in the way.

2026-03-07 18:50 UTC, shirosoluna commented on data/Glitched World/Overworld.json
> +                or (is_child and ((at_day and not gold_skulls_ignore_daytime) or
otherwise no comments from me! thank you for adding advanced logic ❤️

2026-03-07 19:03 UTC, shirosoluna commented on data/Glitched World/Overworld.json
> +                or (is_child and ((at_day and not gold_skulls_ignore_daytime) or
> This is for getting onto granny's potion shop's roof via the watchtower, so the skull is in the way.

ah I see. I was scanning it for the is_adult and is_child making sure they're differentiated. And didnt notice the "not" part. Thanks for clarifying

2026-06-06 10:24 UTC, fenhl commented
Since there were no responses to our previous call for testing, we're going to try posting another one in the new #dev-announcements channel for more visibility. Before we do, could you rebase the PR (or merge Dev) please?

2026-08-10 18:05 UTC, cjohnson57 approved these changes
No real blockers, just a couple small things I noticed. Though, I feel a little impotent in my ability to review this properly, given the scope and the fact that there's thousands of lines of transliterated game data that I can't really have an opinion on.

I kind of wonder if it's worth removing the nighttime skulls expect sun song option now... It feels a bit vestigial. Doesn't do the same thing obviously, but fulfills the role of "I don't want to mess with waiting for night for skulls)

Also, I see this is still tagged as needs testing, is this actually still the case?

2026-08-10 18:05 UTC, cjohnson57 commented on Cutscenes.py
> +    jabu_swallow_cutscene = Cutscene.decode(rom, 0xC9FC84)
Not something that needs to be fixed really but it would be nice if these "magic numbers" could be stored in a table too, like how many of the others have been eliminated by these changes

2026-08-10 18:05 UTC, cjohnson57 commented on Rom.py
> +        return int.from_bytes(self.read_bytes(address, 4), 'big', signed=True)
Is there a particular reason not to make these one function with the size as a param? (Though that being said, I think I might have done the same thing in my model code)

2026-08-10 18:20 UTC, flagrama commented on Rom.py
> +        return int.from_bytes(self.read_bytes(address, 4), 'big', signed=True)
This is pretty standard when working with binary data. Having to specify the size as a parameter just makes each call harder to read because you have to think about which one is the size parameter and may have to refer to the function definition, but by having separate calls for each size makes it obvious. Especially with these being for signed bytes I think it is very important to make it absolutely obvious what the function is doing.

2026-08-10 21:53 UTC, fenhl commented
> Also, I see this is still tagged as needs testing, is this actually still the case?

No, I consider this to be sufficiently tested after the recent full-game test. I guess I forgot to remove the label.

2026-08-10 22:44 UTC, mracsys commented on Cutscenes.py
> +    jabu_swallow_cutscene = Cutscene.decode(rom, 0xC9FC84)
Agreed it could be better documented. Cutscenes are stored all over the place in the codebase with no definitive centralized list unfortunately. This one is in the Jabu actor file for example and only called by it.

The cutscene objects try to minimize the magic VROM locations to just the start of the cutscene. Those are easy to line up with the decomp ntsc-1.0 map file for the cutscene variable address. In the future, maybe there could be a writeup at the top of the file on how to do that.

2026-08-10 22:47 UTC, mracsys commented on Rom.py
> +        return int.from_bytes(self.read_bytes(address, 4), 'big', signed=True)
Basically what flag said. With how often these are called in the parsing functions, it's more ergonomic to do `rom.read_s16(address)` than something like `rom.read_bytes_to_int(address, length, signed=True)`. Also makes it more obvious in the calling code what the C type of the data is supposed to be.

2026-08-10 22:51 UTC, mracsys commented
> > Also, I see this is still tagged as needs testing, is this actually still the case?
> 
> No, I consider this to be sufficiently tested after the recent full-game test. I guess I forgot to remove the label.

To be clear, I've had multiple full-game tests of this on console and emulator for a while in addition to all the individual cases checked off in the PR description. Always preferable to have independent testing though.

2026-08-10 23:14 UTC, fenhl commented
…I was not aware of that.

2026-08-10 23:19 UTC, mracsys commented
I'm not sure I ever said that to be fair, looking back at the description.

2026-08-10 23:21 UTC, fenhl commented
Oh well, like you said, doesn't hurt to have independent confirmation too.

2026-08-20 01:14 UTC, fenhl commented
I'm having trouble merging this because my pre-commit script tries to run unit tests which fail with errors like:

```
======================================================================
ERROR: test_audiobank (Unittest.TestCustomAudio.test_audiobank)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/september-shared/git-stages/github.com/OoTRandomizer/OoT-Randomizer/Unittest.py", line 1052, in test_audiobank
    rom: Rom = Rom("ZOOTDEC.z64")
               ~~~^^^^^^^^^^^^^^^
  File "/mnt/september-shared/git-stages/github.com/OoTRandomizer/OoT-Randomizer/Rom.py", line 46, in __init__
    self.changed_address: numpy.ndarray = numpy.full(134217728, 1000, numpy.uint16)
                                          ^^^^^
NameError: name 'numpy' is not defined
```

This is presumably a quirk of how Python works on NixOS, as adding numpy to the Python packages in the Nix devShell (which I intend to PR in the future) and skipping the venv works:

```nix
python3.withPackages (python-pkgs: with python-pkgs; [
    numpy
])
```

Any objections to adding a `--no-venv` CLI flag that makes `Utils.ensure_venv` return immediately?

2026-08-20 02:03 UTC, mracsys commented
Nope, go for it!

2026-08-20 02:17 UTC, merged